# Generated by Django 3.2.3 on 2021-06-05 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textoPergunta', models.CharField(max_length=200)),
                ('criado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('topico', models.CharField(max_length=100)),
                ('numeroQuestoes', models.IntegerField()),
                ('tempo', models.IntegerField(help_text='duração do quizz em minutos')),
                ('pontuacaoParaPassar', models.IntegerField(help_text='pontos requeritos em %')),
                ('dificuldade', models.CharField(choices=[('fácil', 'fácil'), ('médio', 'médio'), ('dificil', 'dificil')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('apelido', models.CharField(max_length=30)),
                ('telefone', models.CharField(max_length=9)),
                ('email', models.EmailField(max_length=254)),
                ('dataNascimento', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Resultados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontuacao', models.FloatField()),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjetoPW.quiz')),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjetoPW.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textoResposta', models.CharField(max_length=50)),
                ('correta', models.BooleanField(default=False)),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjetoPW.pergunta')),
            ],
        ),
        migrations.AddField(
            model_name='pergunta',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjetoPW.quiz'),
        ),
    ]
