# Generated by Django 3.2.3 on 2021-05-31 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoPW', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('apelido', models.CharField(max_length=30)),
                ('telefone', models.IntegerField(max_length=9)),
                ('email', models.EmailField(max_length=254)),
                ('dataNascimento', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
