# Generated by Django 3.2.3 on 2021-06-19 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoPW', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resposta',
            name='pergunta',
        ),
        migrations.RemoveField(
            model_name='resultados',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='resultados',
            name='utilizador',
        ),
        migrations.DeleteModel(
            name='Pergunta',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='Resposta',
        ),
        migrations.DeleteModel(
            name='Resultados',
        ),
    ]
